name: covid 
channels:
  - conda-forge
  - bioconda
  - daler
  - defaults
dependencies:
  - samtools
  - seqtk
  - megahit
  - multiqc
  - mauve
  - bwa
  - bowtie2
  - fastqc
  - python=3
  - ragtag
  - mafft
  - prokka
  - pilon
  - bcftools
  - fasttree
  - iqtree
  - trimmomatic
  - pangolin
  - snpeff
  - snpsift
  - pip
  - pip:
      - numpy
      - matplotlib
      - matplotlib-venn
      - biopython
      - dREP
